adapters:
  r2dbc:
    host: ${DB_HOST}
    port: 5432
    database: ${DB_NAME}
    schema: public
    username: ${DB_USER}
    password: ${DB_PASS}
  sqs:
    region: ${AWS_REGION}
    queueUrl: ${AWS_QUEUE_URL}
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret: ${JWT_SECRET}