server:
  port: 8081
spring:
  application:
    name: "Loan"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "loan"
    schema: "public"
    username: "loan"
    password: "loan"
logging:
  level:
    root: INFO
    co.com.crediya.loan: DEBUG
auth:
  base-url: http://localhost:8080
jwt:
  secret: "DQpKdWFuIFNhbmNoZXogQm9vdGNhbXAgUG93ZXIgVXAgMjAyNQ"
